#!/bin/bash

bash functionlifecyclemanager_stylecheck.sh
bash placementexecutive_stylecheck.sh
bash placementplugin_stylecheck.sh
bash pluginmanager_stylecheck.sh
bash servicelifecyclemanager_stylecheck.sh
bash sonmanobase_stylecheck.sh
bash specificmanagerregistry_stylecheck.sh
